Models/Client.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace VetClinic.Models
{
    public class Client : Person
    {
        [Display(Name = "Appointments")]
        public virtual ICollection<Appointment> Appointments { get; set; }

        [Display(Name = "Pets")]
        public virtual ICollection<ClientAnimal> ClientAnimals { get; set; }
    }
}

Controllers/AddressesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using VetClinic.Data;
using VetClinic.Models;

namespace VetClinic.Controllers
{
    public class AddressesController : Controller
    {
        private readonly ClinicContext _context;

        public AddressesController(ClinicContext context)
        {
            _context = context;
        }

        // GET: Addresses
        public async Task<IActionResult> Index()
        {
            var clinicContext = _context.PersonAddresses.Include(p => p.Person);
            return View(await clinicContext.ToListAsync());
        }

        // GET: Addresses/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var personAddress = await _context.PersonAddresses
                .Include(p => p.Person)
                .FirstOrDefaultAsync(m => m.PersonAddressId == id);
            if (personAddress == null)
            {
                return NotFound();
            }

            return View(personAddress);
        }

        // GET: Addresses/Create
        public IActionResult Create(long? personId)
        {
            if(personId != null)
            {
                ViewData["PersonId"] = new SelectList(_context.Persons.Where(p => p.PersonId == personId), "PersonId", "FullName");
            } else
            {
                ViewData["PersonId"] = new SelectList(_context.Persons, "PersonId", "FullName");
            }
            
            return View();
        }

        // POST: Addresses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PersonAddressId,PersonId,AddressLine1,AddressLine2,City,State,PostalCode")] PersonAddress personAddress)
        {
            if (ModelState.IsValid)
            {
                _context.Add(personAddress);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", "Clients", new { id = personAddress.PersonId }, null);
            }
            ViewData["PersonId"] = new SelectList(_context.Persons, "PersonId", "FullName", personAddress.PersonId);
            return View(personAddress);
        }

        // GET: Addresses/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var personAddress = await _context.PersonAddresses.FindAsync(id);
            if (personAddress == null)
            {
                return NotFound();
            }
            ViewData["PersonId"] = new SelectList(_context.Persons, "PersonId", "FullName", personAddress.PersonId);
            return View(personAddress);
        }

        // POST: Addresses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("PersonAddressId,PersonId,AddressLine1,AddressLine2,City,State,PostalCode")] PersonAddress personAddress)
        {
            if (id != personAddress.PersonAddressId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(personAddress);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PersonAddressExists(personAddress.PersonAddressId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Details", "Clients", new { id = personAddress.PersonId }, null);
            }
            ViewData["PersonId"] = new SelectList(_context.Persons, "PersonId", "FirstName", personAddress.PersonId);
            return View(personAddress);
        }

        // GET: Addresses/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var personAddress = await _context.PersonAddresses
                .Include(p => p.Person)
                .FirstOrDefaultAsync(m => m.PersonAddressId == id);
            if (personAddress == null)
            {
                return NotFound();
            }

            return View(personAddress);
        }

        // POST: Addresses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var personAddress = await _context.PersonAddresses.FindAsync(id);
            _context.PersonAddresses.Remove(personAddress);
            await _context.SaveChangesAsync();
            return RedirectToAction("Details", "Clients", new { id = personAddress.PersonId }, null);
        }

        private bool PersonAddressExists(long id)
        {
            return _context.PersonAddresses.Any(e => e.PersonAddressId == id);
        }
    }
}

Controllers/EmailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using VetClinic.Data;
using VetClinic.Models;

namespace VetClinic.Controllers
{
    public class EmailsController : Controller
    {
        private readonly ClinicContext _context;

        public EmailsController(ClinicContext context)
        {
            _context = context;
        }

        // GET: Emails
        public async Task<IActionResult> Index()
        {
            var clinicContext = _context.PersonEmails.Include(p => p.Person);
            return View(await clinicContext.ToListAsync());
        }

        // GET: Emails/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var personEmail = await _context.PersonEmails
                .Include(p => p.Person)
                .FirstOrDefaultAsync(m => m.PersonEmailId == id);
            if (personEmail == null)
            {
                return NotFound();
            }

            return View(personEmail);
        }

        // GET: Emails/Create
        public IActionResult Create(long? personId)
        {
            if (personId != null)
            {
                ViewData["PersonId"] = new SelectList(_context.Persons.Where(p => p.PersonId == personId), "PersonId", "FullName");
            }
            else
            {
                ViewData["PersonId"] = new SelectList(_context.Persons, "PersonId", "FullName");
            }
            return View();
        }

        // POST: Emails/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PersonEmailId,PersonId,EmailAddress")] PersonEmail personEmail)
        {
            if (ModelState.IsValid)
            {
                _context.Add(personEmail);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", "Clients", new { id = personEmail.PersonId }, null);
            }
            ViewData["PersonId"] = new SelectList(_context.Persons, "PersonId", "FirstName", personEmail.PersonId);
            return View(personEmail);
        }

        // GET: Emails/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var personEmail = await _context.PersonEmails.FindAsync(id);
            if (personEmail == null)
            {
                return NotFound();
            }
            ViewData["PersonId"] = new SelectList(_context.Persons, "PersonId", "FirstName", personEmail.PersonId);
            return View(personEmail);
        }

        // POST: Emails/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("PersonEmailId,PersonId,EmailAddress")] PersonEmail personEmail)
        {
            if (id != personEmail.PersonEmailId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(personEmail);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PersonEmailExists(personEmail.PersonEmailId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Details", "Clients", new { id = personEmail.PersonId }, null);
            }
            ViewData["PersonId"] = new SelectList(_context.Persons, "PersonId", "FirstName", personEmail.PersonId);
            return View(personEmail);
        }

        // GET: Emails/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var personEmail = await _context.PersonEmails
                .Include(p => p.Person)
                .FirstOrDefaultAsync(m => m.PersonEmailId == id);
            if (personEmail == null)
            {
                return NotFound();
            }

            return View(personEmail);
        }

        // POST: Emails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var personEmail = await _context.PersonEmails.FindAsync(id);
            _context.PersonEmails.Remove(personEmail);
            await _context.SaveChangesAsync();
            return RedirectToAction("Details", "Clients", new { id = personEmail.PersonId }, null);
        }

        private bool PersonEmailExists(long id)
        {
            return _context.PersonEmails.Any(e => e.PersonEmailId == id);
        }
    }
}

Controllers/PhonesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using VetClinic.Data;
using VetClinic.Models;

namespace VetClinic.Controllers
{
    public class PhonesController : Controller
    {
        private readonly ClinicContext _context;

        public PhonesController(ClinicContext context)
        {
            _context = context;
        }

        // GET: Phones
        public async Task<IActionResult> Index()
        {
            var clinicContext = _context.PersonPhones.Include(p => p.Person);
            return View(await clinicContext.ToListAsync());
        }

        // GET: Phones/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var personPhone = await _context.PersonPhones
                .Include(p => p.Person)
                .FirstOrDefaultAsync(m => m.PersonPhoneId == id);
            if (personPhone == null)
            {
                return NotFound();
            }

            return View(personPhone);
        }

        // GET: Phones/Create
        public IActionResult Create(long? personId)
        {
            if (personId != null)
            {
                ViewData["PersonId"] = new SelectList(_context.Persons.Where(p => p.PersonId == personId), "PersonId", "FullName");
            }
            else
            {
                ViewData["PersonId"] = new SelectList(_context.Persons, "PersonId", "FullName");
            }

            return View();
        }

        // POST: Phones/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PersonPhoneId,PersonId,PhoneNumber")] PersonPhone personPhone)
        {
            if (ModelState.IsValid)
            {
                _context.Add(personPhone);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", "Clients", new { id = personPhone.PersonId }, null);
            }
            ViewData["PersonId"] = new SelectList(_context.Persons, "PersonId", "FirstName", personPhone.PersonId);
            return View(personPhone);
        }

        // GET: Phones/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var personPhone = await _context.PersonPhones.FindAsync(id);
            if (personPhone == null)
            {
                return NotFound();
            }
            ViewData["PersonId"] = new SelectList(_context.Persons, "PersonId", "FirstName", personPhone.PersonId);
            return View(personPhone);
        }

        // POST: Phones/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("PersonPhoneId,PersonId,PhoneNumber")] PersonPhone personPhone)
        {
            if (id != personPhone.PersonPhoneId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(personPhone);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PersonPhoneExists(personPhone.PersonPhoneId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Details", "Clients", new { id = personPhone.PersonId }, null);
            }
            ViewData["PersonId"] = new SelectList(_context.Persons, "PersonId", "FirstName", personPhone.PersonId);
            return View(personPhone);
        }

        // GET: Phones/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var personPhone = await _context.PersonPhones
                .Include(p => p.Person)
                .FirstOrDefaultAsync(m => m.PersonPhoneId == id);
            if (personPhone == null)
            {
                return NotFound();
            }

            return View(personPhone);
        }

        // POST: Phones/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var personPhone = await _context.PersonPhones.FindAsync(id);
            _context.PersonPhones.Remove(personPhone);
            await _context.SaveChangesAsync();
            return RedirectToAction("Details", "Clients", new { id = personPhone.PersonId }, null);
        }

        private bool PersonPhoneExists(long id)
        {
            return _context.PersonPhones.Any(e => e.PersonPhoneId == id);
        }
    }
}

Views/Clients/Create.cshtml
@model VetClinic.Models.Client

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Client</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Clients/Delete.cshtml
@model VetClinic.Models.Client

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Client</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="PersonId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Clients/Details.cshtml
@model VetClinic.Models.Client

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Client</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FullName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FullName)<span class="float-right"><a asp-action="Edit" asp-route-id="@Model.PersonId">Edit</a></span>
        </dd>
        <dt class="col-sm-2 mt-3">
            @Html.DisplayNameFor(model => model.PersonAddresses)
        </dt>
        <dd class="col-sm-10 mt-3">
            @if (Model.PersonAddresses.Count > 0)
            {
                <table class="table table-sm table-striped">
                    <thead>
                        <tr>
                            <th>Street Address</th>
                            <th>City</th>
                            <th>State</th>
                            <th>Postal Code</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.PersonAddresses)
                        {
                            <tr>
                                <td>@Html.DisplayFor(modelItem => item.AddressLine1) @Html.DisplayFor(modelItem => item.AddressLine2)</td>
                                <td>@Html.DisplayFor(modelItem => item.City)</td>
                                <td>@Html.DisplayFor(modelItem => item.State)</td>
                                <td>@Html.DisplayFor(modelItem => item.PostalCode)</td>
                                <td>
                                    <a asp-controller="Addresses" asp-action="Edit" asp-route-id="@item.PersonAddressId">Edit</a> |
                                    <a asp-controller="Addresses" asp-action="Delete" asp-route-id="@item.PersonAddressId">Delete</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            }
            else
            {
                <div class="alert alert-info">No addresses on file for this client.</div>
            }
            <div class="w-100 clearfix"><a class="btn btn-sm btn-primary float-right" asp-controller="Addresses" asp-action="Create" asp-route-personid="@Model.PersonId"><i class="fas fa-plus pr-1"></i>Add</a></div>
        </dd>
        <dt class="col-sm-2 mt-3">
            Contact Info
        </dt>
        <dd class="col-sm-10 mt-3">
            @if (Model.PersonPhones.Count > 0)
            {
                <table class="table table-sm table-striped">
                    <thead>
                        <tr>
                            <th>Phone Number</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.PersonPhones)
                        {
                            <tr>
                                <td>@Html.DisplayFor(modelItem => item.PhoneNumber)</td>
                                <td>
                                    <a asp-controller="Phones" asp-action="Edit" asp-route-id="@item.PersonPhoneId">Edit</a> |
                                    <a asp-controller="Phones" asp-action="Delete" asp-route-id="@item.PersonPhoneId">Delete</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            }
            else
            {
                <div class="alert alert-info">No phone numbers on file for this client.</div>
            }
            <div class="w-100 clearfix"><a class="btn btn-sm btn-primary float-right" asp-controller="Phones" asp-action="Create" asp-route-personid="@Model.PersonId"><i class="fas fa-plus pr-1"></i>Add</a></div>

            @if (Model.PersonEmails.Count > 0)
            {
                <table class="table table-sm table-striped mt-3">
                    <thead>
                        <tr>
                            <th>Email Addresses</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.PersonEmails)
                        {
                            <tr>
                                <td>@Html.DisplayFor(modelItem => item.EmailAddress)</td>
                                <td>
                                    <a asp-controller="Emails" asp-action="Edit" asp-route-id="@item.PersonEmailId">Edit</a> |
                                    <a asp-controller="Emails" asp-action="Delete" asp-route-id="@item.PersonEmailId">Delete</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            }
            else
            {
                <div class="alert alert-info">No email addresses on file for this client.</div>
            }
            <div class="w-100 clearfix"><a class="btn btn-sm btn-primary float-right" asp-controller="Emails" asp-action="Create" asp-route-personid="@Model.PersonId"><i class="fas fa-plus pr-1"></i>Add</a></div>
        </dd>
        <dt class="col-sm-2 mt-3">
            @Html.DisplayNameFor(model => model.ClientAnimals)
        </dt>
        <dd class="col-sm-10 mt-3">
            @if (Model.ClientAnimals.Count() > 0)
            {
                <table class="table table-sm table-striped">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Birth Date</th>
                            <th>Species</th>
                            <th>Notes</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.ClientAnimals)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.BirthDate)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Species.Name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Notes)
                                </td>
                                <td>
                                    <a asp-controller="ClientAnimals" asp-action="Edit" asp-route-id="@item.ClientAnimalId">Edit</a> |
                                    <a asp-controller="ClientAnimals" asp-action="Delete" asp-route-id="@item.ClientAnimalId">Delete</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            }
            else
            {
                <div class="alert alert-info">No pets on file for this client.</div>
            }
        <div class="w-100 clearfix"><a class="btn btn-sm btn-primary float-right" asp-controller="ClientAnimals" asp-action="Create" asp-route-personid="@Model.PersonId"><i class="fas fa-plus pr-1"></i>Add</a></div>
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Clients/Edit.cshtml
@model VetClinic.Models.Client

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Client</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PersonId" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Clients/Index.cshtml
@model IEnumerable<VetClinic.Models.Client>

@{
    ViewData["Title"] = "Clients";
}

<h1>Clients</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    <a asp-action="Details" asp-route-id="@item.PersonId">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.PersonId">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>