Controllers/AppointmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using VetClinic.Data;
using VetClinic.Models;

namespace VetClinic.Controllers
{
    public class AppointmentsController : Controller
    {
        private readonly ClinicContext _context;

        public AppointmentsController(ClinicContext context)
        {
            _context = context;
        }

        // GET: Appointments
        public async Task<IActionResult> Index(string sortOrder)
        {
            ViewData["AppointmentDateSortParm"] = String.IsNullOrEmpty(sortOrder) ? "date_desc" : "";
            ViewData["PetSortParm"] = sortOrder == "Pet" ? "pet_desc" : "Pet";
            ViewData["ClientSortParm"] = sortOrder == "Client" ? "client_desc" : "Client";
            ViewData["EmployeeSortParm"] = sortOrder == "Employee" ? "employee_desc" : "Employee";

            var appointments = from a in _context.Appointments.Include(a => a.Employee).Include(a => a.ClientAnimal).ThenInclude(a => a.Client)
                               select a;

            switch (sortOrder)
            {
                case "date_desc":
                    appointments = appointments.OrderByDescending(s => s.AppointmentDate);
                    break;
                case "pet_desc":
                    appointments = appointments.OrderByDescending(s => s.ClientAnimal.Name);
                    break;
                case "Pet":
                    appointments = appointments.OrderBy(s => s.ClientAnimal.Name);
                    break;
                case "client_desc":
                    appointments = appointments.OrderByDescending(s => s.ClientAnimal.Client.LastName);
                    break;
                case "Client":
                    appointments = appointments.OrderBy(s => s.ClientAnimal.Client.LastName);
                    break;
                case "employee_desc":
                    appointments = appointments.OrderByDescending(s => s.Employee.LastName);
                    break;
                case "Employee":
                    appointments = appointments.OrderBy(s => s.Employee.LastName);
                    break;
                default:
                    appointments = appointments.OrderBy(a => a.AppointmentDate);
                    break;
            }

            return View(await appointments.AsNoTracking().ToListAsync());
        }

        // GET: Appointments/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appointment = await _context.Appointments
                .Include(a => a.Employee)
                .Include(a => a.ClientAnimal)
                    .ThenInclude(a => a.Client)
                .FirstOrDefaultAsync(m => m.AppointmentId == id);
            if (appointment == null)
            {
                return NotFound();
            }

            return View(appointment);
        }

        // GET: Appointments/Create
        public IActionResult Create()
        {
            ViewData["ClientAnimalId"] = new SelectList(_context.ClientAnimals, "ClientAnimalId", "Name");
            ViewData["EmployeeId"] = new SelectList(_context.Employees, "PersonId", "FullName");
            return View();
        }

        // POST: Appointments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AppointmentId,ClientAnimalId,EmployeeId,AppointmentDate,Reason")] Appointment appointment)
        {
            if (ModelState.IsValid)
            {
                _context.Add(appointment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClientAnimalId"] = new SelectList(_context.ClientAnimals, "ClientAnimalId", "Name", appointment.ClientAnimalId);
            ViewData["EmployeeId"] = new SelectList(_context.Employees, "PersonId", "FullName", appointment.EmployeeId);
            return View(appointment);
        }

        // GET: Appointments/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appointment = await _context.Appointments.FindAsync(id);
            if (appointment == null)
            {
                return NotFound();
            }
            ViewData["ClientAnimalId"] = new SelectList(_context.ClientAnimals, "ClientAnimalId", "Name", appointment.ClientAnimalId);
            ViewData["EmployeeId"] = new SelectList(_context.Employees, "PersonId", "FullName", appointment.EmployeeId);
            return View(appointment);
        }

        // POST: Appointments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("AppointmentId,ClientAnimalId,EmployeeId,AppointmentDate,Reason")] Appointment appointment)
        {
            if (id != appointment.AppointmentId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(appointment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AppointmentExists(appointment.AppointmentId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClientAnimalId"] = new SelectList(_context.ClientAnimals, "ClientAnimalId", "Name", appointment.ClientAnimalId);
            ViewData["EmployeeId"] = new SelectList(_context.Employees, "PersonId", "FullName", appointment.EmployeeId);
            return View(appointment);
        }

        // GET: Appointments/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appointment = await _context.Appointments
                .Include(a => a.ClientAnimal)
                .Include(a => a.Employee)
                .FirstOrDefaultAsync(m => m.AppointmentId == id);
            if (appointment == null)
            {
                return NotFound();
            }

            return View(appointment);
        }

        // POST: Appointments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var appointment = await _context.Appointments.FindAsync(id);
            _context.Appointments.Remove(appointment);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AppointmentExists(long id)
        {
            return _context.Appointments.Any(e => e.AppointmentId == id);
        }
    }
}

Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using VetClinic.Data;
using VetClinic.Models;

namespace VetClinic.Controllers
{
    public class ClientsController : Controller
    {
        private readonly ClinicContext _context;

        public ClientsController(ClinicContext context)
        {
            _context = context;
        }

        // GET: Clients
        public async Task<IActionResult> Index()
        {
            return View(await _context.Clients.ToListAsync());
        }

        // GET: Clients/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = await _context.Clients
                .Include(c => c.PersonAddresses)
                .Include(c => c.PersonPhones)
                .Include(c => c.PersonEmails)
                .Include(c => c.ClientAnimals)
                    .ThenInclude(sp => sp.Species)
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.PersonId == id);

            if (client == null)
            {
                return NotFound();
            }

            return View(client);
        }

        // GET: Clients/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Clients/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PersonId,FirstName,LastName")] Client client)
        {
            if (ModelState.IsValid)
            {
                _context.Add(client);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(client);
        }

        // GET: Clients/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = await _context.Clients.FindAsync(id);
            if (client == null)
            {
                return NotFound();
            }
            return View(client);
        }

        // POST: Clients/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("PersonId,FirstName,LastName")] Client client)
        {
            if (id != client.PersonId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(client);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClientExists(client.PersonId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(client);
        }

        // GET: Clients/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = await _context.Clients
                .FirstOrDefaultAsync(m => m.PersonId == id);
            if (client == null)
            {
                return NotFound();
            }

            return View(client);
        }

        // POST: Clients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var client = await _context.Clients.FindAsync(id);
            _context.Clients.Remove(client);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClientExists(long id)
        {
            return _context.Clients.Any(e => e.PersonId == id);
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using VetClinic.Models;

namespace VetClinic.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Welcome";
}


<div class="row">
    <div class="col-sm-12">
        <img class="mx-auto d-block img-fluid" src="~/images/4198540.jpg" style="max-height:500px;" />
    </div>
    <div class="col-sm-12 mt-5">
        <div class="row">
            <div class="col-sm-4 mt-3">
                <div class="card">
                    <div class="card-header text-center">
                        <div class="d-flex align-items-center">
                            <span class="mx-auto w-100 display-4"><i class="far fa-calendar-alt ml-auto"></i></span>

                        </div>
                    </div>
                    <div class="card-body">
                        <a class="btn btn-primary btn-block" asp-area="" asp-controller="Appointments" asp-action="Index">Current Appointments</a>
                    </div>
                </div>
            </div>

            <div class="col-sm-4 mt-3">
                <div class="card">
                    <div class="card-header text-center">
                        <div class="d-flex align-items-center">
                            <span class="mx-auto w-100 display-4"><i class="fas fa-user ml-auto"></i></span>

                        </div>
                    </div>
                    <div class="card-body">
                        <a class="btn btn-primary btn-block" asp-area="" asp-controller="Clients" asp-action="Create">Add Clients</a>
                    </div>
                </div>
            </div>

            <div class="col-sm-4 mt-3">
                <div class="card">
                    <div class="card-header text-center">
                        <div class="d-flex align-items-center">
                            <span class="mx-auto w-100 display-4"><i class="far fa-calendar-alt ml-auto"></i></span>
                        </div>
                    </div>
                    <div class="card-body">
                        <a class="btn btn-primary btn-block" asp-area="" asp-controller="Appointments" asp-action="Create">Add Appointments</a>
                    </div>
                </div>
            </div>
        </div>




    </div>
</div>

@*<div class="container mt-2">
    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header text-center bg-dark text-white">
                    <div class="d-flex align-items-center">
                        <span class="mx-auto w-100 display-1"><i class="fas fa-user ml-auto"></i></span>

                    </div>
                </div>
                <div class="card-body">
                    <a class="btn btn-warning btn-lg btn-block" asp-area="" asp-controller="Clients" asp-action="Index">Clients</a>
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="card">
                <div class="card-header text-center bg-dark text-white">
                    <div class="d-flex align-items-center">
                        <span class="mx-auto w-100 display-1"><i class="far fa-calendar-alt ml-auto"></i></span>

                    </div>
                </div>
                <div class="card-body">
                    <a class="btn btn-warning btn-lg btn-block" asp-area="" asp-controller="Appointments" asp-action="Index">Appointments</a>
                </div>
            </div>
        </div>
    </div>
</div>*@